# application.yml
--- 
spring: 
  application: 
    name: ServizioA
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server: 
  port: ${PORT:${SERVER_PORT:0}}
# port: 8080
uname: DefaultProfile
feign:
  client: servizioc
--- 
spring: 
  profiles: alice
  application: 
    name: servizioa
uname: Alice
feign:
  client: servizioc  
--- 
spring: 
  profiles: alberto
  application: 
    name: servizioa
uname: Alberto
feign:
  client: servizioc