version: '3'

services:
  eureka-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    ports: 
      - "8761:8761"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "asw.kafka.channel.alpha:4:1"
  servizioa:
    depends_on:
      - "eureka-server"
      - "kafka"
    build:
      context: servizioA
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
  serviziob:
    depends_on:
      - "eureka-server"
      - "kafka"
    build:
      context: servizioB
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  servizioc:
    depends_on:
      - "eureka-server"
    build:
      context: servizioC
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  zuul:
    depends_on:
      - "eureka-server"
      - "servizioa"
      - "serviziob"
      - "servizioc"
    build:
      context: zuul-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
