# application.yml
--- 
spring: 
  application: 
    name: ServizioA
eureka: 
  client: 
    serviceUrl: 
#     defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/	
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server: 
  port: ${PORT:${SERVER_PORT:0}}
# port: 8080
uname: DefaultProfile
feign:
  client: servizioc
--- 
spring: 
  profiles: alice
  application: 
    name: servizioa
uname: Alice
feign:
  client: servizioc  
--- 
spring: 
  profiles: alberto
  application: 
    name: servizioa
uname: Alberto
feign:
  client: servizioc
---
#spring.main.web-application-type: 'NONE '
asw:
  progetto:
    channel:
      out: asw.kafka.channel.alpha
    groupid: simple-producer

spring:
  kafka:
#    bootstrap-servers: localhost:9092
    bootstrap-servers: ${DOCKER_HOST_IP}:9092
    consumer:
      group-id: ${asw.kafka.groupid}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
         spring.json.trusted.packages: '*'
    producer:
      key-serializer: 
        org.apache.kafka.commongroup-id: ${asw.kafka.groupid}.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
