# application.yml
--- 
spring: 
  application: 
    name: ServizioC
eureka: 
  client: 
    serviceUrl: 
#     defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/
  instance: 
    leaseRenewalIntervalInSeconds: 10
    metadataMap: 
      instanceId: ${spring.application.name}:${random.value}
server: 
  port: ${PORT:${SERVER_PORT:0}}
# port: 8080
uname: DefaultProfile
--- 
spring: 
  profiles: carlo
  application: 
    name: servizioc
uname: Carlo  
--- 
spring: 
  profiles: chiara
  application: 
    name: servizioc
uname: Chiara
